package lib
/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'pditommaso' at '4/22/14 11:51 AM' with Gradle 1.10
 *
 * @author pditommaso, @date 4/22/14 11:51 AM
 */
class Library {

    static void sayHello(String self) {
        println "Hello world!"
    }

}
